services
    node-red
        depends_on
            - influx
        container_name nodered-qbee
        build {{nodered-image-path}}
        image nodered-influx{{nodered-image-version}}
        environment
            - TZ=EuropeAmsterdam
            - FLOWS={{nodered-flow}}
        ports
            - {{nodered-port}}1880
        volumes
            - {{nodered-data-path}}data

    influx
        container_name influx-qbee
        image influxdb{{influx-image-version}}
        environment
            - INFLUXDB_HTTP_AUTH_ENABLED=TRUE
            - INFLUXDB_ADMIN_USER={{influx-admin-user}}
            - INFLUXDB_ADMIN_PASSWORD={{influx-admin-pw}}
            - INFLUXDB_USER={{influx-rw-user}}
            - INFLUXDB_USER_PASSWORD={{influx-rw-pw}}
            - INFLUXDB_READ_USER={{influx-read-user}}
            - INFLUXDB_READ_USER_PASSWORD={{influx-read-pw}}
            - INFLUXDB_DB={{influx-database}}
            - INFLUXDB_RETENTION_NAME={{influx-retpol-name}}
            - INFLUXDB_RETENTION_DURATION={{influx-retpol-duration}}
            - INFLUXDB_RETENTION_REPLICATION={{influx-retpol-repl}}
        volumes
            - influx-storagevarlibinfluxdb
            - {{influx-init-path}}init-influxdb.shinit-influxdb.sh

    grafana
        depends_on
            - influx
        container_name grafana-qbee
        image grafanagrafana{{grafana-image-version}}
        environment
            - GF_SECURITY_ADMIN_USER={{grafana-admin-user}}
            - GF_SECURITY_ADMIN_PASSWORD={{grafana-admin-pw}}
            - GF_PATHS_PROVISIONING=vargrafana-dockerprovisioning
            - GRAFANA_INFLUX_DB={{influx-database}}
            - GRAFANA_INFLUX_USER={{influx-read-user}}
            - GRAFANA_INFLUX_PASSWORD={{influx-read-pw}}
        volumes
            - grafana-storagevarlibgrafana
            - {{grafana-path}}provisioningvargrafana-dockerprovisioning
        ports
            - {{grafana-port}}3000

volumes
    grafana-storage
    influx-storage